<?php

namespace app\modules\agent;

use app\models\Agent;
use app\models\WxOpenApp;
use app\models\WxOpenWebAppUser;
use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\WxOpenWebApp;

class AdminController extends Controller
{
    public $layout = 'admin';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    //统一报错AJAX
    protected function errorAjax(\Exception $e){
        return json_encode(['errcode'=>$e->getCode(),'errmsg'=>$e->getMessage().$e->getFile().$e->getLine()],JSON_UNESCAPED_UNICODE);
    }
    //统一成功JAX
    protected function successAjax($arr = []){
        return json_encode(array_merge(['errcode'=>0,'errmsg'=>'','result'=>$arr]),JSON_UNESCAPED_UNICODE);
    }
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
//        print_r(Yii::$app->user);
//        echo Yii::$app->user->isGuest;exit;
        if (Yii::$app->user->isGuest) {
            $this->redirect('/');
        }
        return true;
    }

}
